version: '2.1'
services:

  jenkins:
    restart: always
    image: jenkins:latest
    container_name: dc_jenkins
    ports:
#     - "${HTTP_BIND:-0.0.0.0}:${HTTP_PORT:-3000}:${HTTP_PORT:-3000}"
     - "${JENKINS_INTER_BIND:-0.0.0.0}:${JENKINS_INTER_PORT:-50000}:${JENKINS_INTER_PORT:-50000}"
    volumes:
     - ./data/jenkins/:/var/jenkins_home:rw
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST=${PUBLIC_FQDN}
      - VIRTUAL_PORT=${HTTP_PORT:-80}
      - LETSENCRYPT_HOST=${PUBLIC_FQDN}
      - LETSENCRYPT_EMAIL=${ADMIN_MAIL}
      - JENKINS_USERNAME=${JENKINS_ADMIN}
      - JENKINS_PASSWORD=${JENKINS_PASS}

